### ISSUE TITLE
Configure different logging levels per sink

### ISSUE THREAD

**Issue by severisv** [serilog/serilog-settings-configuration#135] opened 2018-09-27 11:23 UTC
Is it possible to set up different logging levels per sink?

**Comment by tsimbalar** [comment] 2018-09-27 12:50
Hi,

yes, sink configuration methods usually provide a `restrictedToMinimumLevel` parameter that can be passed. (it cannot enable levels that are disabled at the global Serilog pipeline level, though)

This parameter is also available through the JSON configuration.

More info in the wiki : https://github.com/serilog/serilog/wiki/Configuration-Basics#overriding-per-sink

**Comment by severisv** [comment] 2018-09-28 09:35
Thanks for replying. To be more precise I'm currently configuring a different log level per namespace like this:

```json
    "Serilog": {
      "MinimumLevel": {
        "Default": "Debug",
        "Override": {
          "System": "Warning",
          "Microsoft": "Warning"
        }     
      }
    },
```

I would like my console sink to log information from these namespaces, but not my other sinks.

I don't quite understand how I can achieve this with `restrictedToMinimumLoglevel`.

I still want my other sinks to log information from other namespaces.

**Comment by MV10** [comment] 2018-09-30 18:48
That's a duplicate of #93 and the answer is that it's up to each sink (see that issue for a bit more detail about why).

**Comment by mochangping** [comment] 2019-07-16 15:02
Hi, were you able to solve this issue? @severisv

**Comment by skomis-mm** [comment] 2020-05-12 23:23
Duplicate of [#93](https://github.com/serilog/serilog-settings-configuration/issues/93), possible solution can be checked there.

**Closed by skomis-mm** 2020-05-12 23:23 UTC
