### ISSUE TITLE
.NET Framework: Configuring Enrichers from json does not work

### ISSUE THREAD

**Issue by aFuerst** [serilog/serilog-settings-configuration#122] opened 2018-07-19 19:53 UTC
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog, Version=2.0.0.0
Serilog.Enrichers.Process, Version=2.0.0.0
Serilog.Enrichers.Thread, Version=2.0.0.0
Serilog.Enrichers.Environment, Version=2.0.0.0
Serilog.Settings.Configuration, Version=2.6.1.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [X] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Enrichers configured via json configuration are not applied. 
The created logger has an empty enricher.

**Please describe the expected behavior?**
The enrichers specified in the json config should be applied to the created logger and the data they are supposed to add gets put in the logs

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
This is the config section I have
```json
"Serilog": {
	"Enrich": [ "FromLogContext", "WithMachineName", "WithProcessId", "WithThreadId", "WithExceptionDetails" ],
	"MinimumLevel": "Verbose",
	"WriteTo": [
		{
			"Name": "Trace",
			"Args": {
				"formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog"
			}
		}
	],
	"Using": [ "Serilog.Sinks.Trace" ]
}
```
We're using the full .NET Framework. 
The logger creation looks like this. We load it entirely from the IConfiguration object.
```csharp
var logger = new LoggerConfiguration()
	.ReadFrom.Configuration(config)
	.CreateLogger();
```

**Comment by merbla** [comment] 2018-07-19 21:40
@aFuerst are you missing a using in the settings for `Serilog.Enrichers.Environment?

```
"Using": [ "Serilog.Sinks.Trace", "Serilog.Enrichers.Environment" ]
```

**Comment by aFuerst** [comment] 2018-07-20 13:38
@merbla That was it. Thank you!
I didn't realize I needed to add the namespaces to the `Using` since you didn't do that in the example in the ReadMe

**Comment by tsimbalar** [comment] 2018-07-20 14:04
Actually the [README](https://github.com/serilog/serilog-settings-configuration) says : 

> (This package implements a convention using DependencyContext to find any package with Serilog anywhere in the name and pulls configuration methods from it, so the Using example above is redundant.)

So we are actually saying that `"Using"` is not necessary for `Serilog.*` libraries, and the following code does it : https://github.com/serilog/serilog-settings-configuration/blob/74fb413e2cbaeeea7aee8afe9aab1b9943a38822/src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs#L297-L302

So there is either a bug or an incorrect documentation issue here :)

**Comment by MV10** [comment] 2018-07-20 16:00
Is there a test for that? Sounds like we need one if not.

**Comment by tsimbalar** [comment] 2018-07-20 16:09
The sample app does not specify `"Using"` for `WriteTo.Async` or `Enrich.WithMachineName` that leave in separate Nuget packages, so something is slightly wrong somewhere ....

**Comment by marco-gallinari** [comment] 2018-07-25 19:34
We are experiencing the same issue adding serilog to a 4.6.1 web project via ninject.
The project is hosting a suite of wcf services, and we need to inject netstandard dependencies from other .net core projects.

The library is not loading enrichers nor sinks (File and Seq).

`
kernel.Bind<ILoggerFactory>().ToMethod(context => {

                var conf = context.Kernel.Get<IConfiguration>();


                var loggerConfig = new LoggerConfiguration();

                loggerConfig.ReadFrom.Configuration(conf);

                return new LoggerFactory().AddSerilog(loggerConfig.CreateLogger(), true);

            }).InSingletonScope();
            kernel.Bind(typeof(ILogger<>)).To(typeof(Logger<>)).InSingletonScope();
`

It only works as soon as we add all namespaces (enrichers and sinks) to the "Using" property.

This could be an issue with the framework version, because the same json configuration works properly on our .net core projects.

**Comment by nblumhardt** [comment] 2018-07-25 21:52
Ah, yes, the "Using" blocks are only redundant in Core, IIRC the dependency context works differently on Framework :-/

**Comment by skomis-mm** [comment] 2019-01-07 13:46
fixed by [#159](https://github.com/serilog/serilog-settings-configuration/pull/159)

**Closed by skomis-mm** 2019-01-07 13:46 UTC

**Comment by mikeblas** [comment] 2019-12-08 15:35
I'm experiencing this same issue. I'm using Core 3.1, though, so maybe something is broken in a different way than was previous fixed.

My config file has these lines that seem relevant:

```
    "Using": [ "Serilog.Sinks.Console", "Serilog.Enrichers.Thread", "Serilog.Enrichers.Environment", "Serilog.Sinks.File" ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
```

The rest of my configuration seems to work, so I'm not sure what else I might check. I don't notice any error messages or exceptions ...

**Comment by skomis-mm** [comment] 2019-12-13 16:09
Hi, @mikeblas . Just checked with 3.1 - works as expected. Can you provide your setup or minimal code that reproduce this? Thanks!
