### ISSUE TITLE
LoggingLevelSwitch support

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-settings-configuration#69] opened 2017-09-28 22:32 UTC
See: https://github.com/serilog/serilog-settings-appsettings/issues/7

**Comment by tsimbalar** [comment] 2017-12-22 21:28
Implementation from serilog/serilog#1020 can be used as a starting point.

Maybe this issue could be flagged as `up-for grabs` ?

**Comment by tsimbalar** [comment] 2018-01-18 21:52
What should the syntax look like ? 

I'm thinking : 

```json
{
  "Serilog": {
    "Using": [ "TestDummies" ],
    "LevelSwitches": [
      { "$mySwitch": "Warning" }
    ],
    "MinimumLevel": {
      "ControlledBy": "$mySwitch"
    },
    "WriteTo": [
      {
        "Name": "DummyWithLevelSwitch",
        "Args": {
          "controlLevelSwitch": "$mySwitch"
        }
      }
    ]
  }
}
```

Would that make sense ?

**Comment by nblumhardt** [comment] 2018-01-18 22:33
LGTM!

**Comment by shobhitkasliwal** [comment] 2018-02-08 18:23
I tired this but I am getting an error in my Asp.net core 2.0 web application - "The value '$mySwitch' is not a valid Serilog level". 
does these controlswitch setting is working for any one ?

**Comment by tsimbalar** [comment] 2018-02-08 19:28
Hi @shobhitkasliwal ,
the feature is not implemented yet, and that is why the issue is still open. 

The configuration snippet is just a proposal of what the configuration may look like. 

The issue is marked as *up-for-grabs* so you are welcome to try and start a Pull Request and we can try to help you :)

Cheers !

**Comment by tsimbalar** [comment] 2018-02-11 12:18
I'm having second thoughts about what the configuration should look like in json ..

Should the "level switches" declaration section be : 

```json
"LevelSwitches": [
      { "$mySwitch": "Warning" },
      { "$myOtherSwitch": "Debug },     
    ]
```

or 

```json
"LevelSwitches": { 
    "$mySwitch": "Warning" 
    "$myOtherSwitch": "Debug" 
}
```

It is a *collection* of switches, but somehow it really is a dictionary *name -> LogLevelSwitch*, so the second syntax makes sense and is a bit less verbose ...

Any opinion ? :)

**Comment by KorsG** [comment] 2018-02-11 13:02
I vote for the 2nd example 👍 
It makes more sense for it to be a property bag, since it naturally eliminates duplicates :-)

![image](https://user-images.githubusercontent.com/1583564/36073632-14cccf0e-0f34-11e8-87e8-4d1784f10253.png)

**Comment by tsimbalar** [comment] 2018-02-12 07:01
I have issued a PR #88 that implements that format. Feedback is welcome :)

**Closed** 2018-02-13 22:29 UTC
Labels: enhancement
