### ISSUE TITLE
Parameter-matching is case-sensitive (sink arguments, etc)

### ISSUE THREAD

**Issue by josephgardner** [serilog/serilog-settings-configuration#111] opened 2018-05-09 18:51 UTC
I'm trying to set the formatter using Environment Variables, and nothing I've tried is working. 

I was able to set it using an in-memory configuration, so I'm pretty sure the syntax is correct:

```
var defaultConfig = new Dictionary<string, string>
{
    { "Serilog:WriteTo:0:Name", "Trace" },
    { "Serilog:WriteTo:0:Args:formatter", "Serilog.Formatting.Json.JsonFormatter, Serilog" }
}

var builder = new ConfigurationBuilder()
    .AddInMemoryCollection(defaultConfig)
    .AddEnvironmentVariables("IDP_");
```

All of my other environment variables are loaded by configuration correctly, just not Serilog.

Any suggestions?

```
IDP_SERILOG__WRITETO__0__NAME='Trace' 
IDP_SERILOG__WRITETO__0__ARGS__FORMATTER='Serilog.Formatting.Json.JsonFormatter, Serilog' 
```

```
IDP_Serilog:WriteTo:0:Name='Trace'
IDP_Serilog:WriteTo:0:Args:formatter='Serilog.Formatting.Json.JsonFormatter, Serilog'
```

Adding a breakpoint, I'm able to see the values are loaded in the config object correctly
![image](https://user-images.githubusercontent.com/1297859/39836832-ad9ccd62-53a2-11e8-99ec-52653d3cbae6.png)

**Comment by josephgardner** [comment] 2018-05-09 20:44
I was able to get this working using. The environment variables are **case sensitive**. I believe environment variables should be case insensitive?

```yml
    environment:
      - IDP_Serilog__MinimumLevel=Debug
      - IDP_Serilog__WriteTo__0__Name=Trace
      - IDP_Serilog__WriteTo__0__Args__formatter=Serilog.Formatting.Json.JsonFormatter, Serilog
```

**Comment by MV10** [comment] 2018-05-09 21:26
I noticed a case-sensitivity issue while working on a related problem. Combined with the fact that most configuration is moving towards JSON and it has different default casing rules than this package uses (JSON is normally camel-case, C# and this repo tends towards Pascal-case), this should probably be regarded as a bug.

And I'll probably fix it because it bothers me.

**Comment by merbla** [comment] 2018-05-09 21:38
@josephgardner @MV10 there maybe implications changing case sensitivity on other platforms (*nix, OSX).

What platforms are you targeting?

**Comment by MV10** [comment] 2018-05-09 21:58
@merbla _Microsoft.Extensions.Configuration_ is case-sensitive irrespective of platform ... but it's my personal opinion that this is a Very Bad Idea. Not because I just don't like it (which is true), but because different configuration sources could have different casing conventions or rules, which directly conflicts with the concept of overlaying settings from different sources.

I did some searching and found a couple tangentially-related MS github discussions about config key case-sensitivity but nothing looked definitive -- no statement akin to, "We decided the rule is XYZ and that's what everyone should expect."

I'm tempted to open a question on the subject in an MS repo.

**Comment by josephgardner** [comment] 2018-05-09 22:07
According to [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration), 

> Configuration keys are **not** case-sensitive.

**Comment by MV10** [comment] 2018-05-09 22:19
@josephgardner I just came back to post the same thing, but there are some weird decisions within the .NET Core repos: they refer things like _Configuration_ to the ASP.NET Core team, even though their config package isn't specific to ASP.NET Core. (This is true of many things that came from the ASP.NET world but are now stand-alone in Core ... dependency injection is another major example. There is a serious case of web-app-blinders over there right now.)

Regardless, I agree with you, it should be case-insensitive. We _know_ the config system itself is case-sensitive (or we wouldn't be having this conversation) so I'm guessing that's something the ASP.NET Core team does differently (and so far, MS has chosen to ignore documenting config for any other use-case). Hopefully there is an easily-applied fix of some kind. (It would be great if this turns out to be an option you can set in the config-builder stage.)

**Comment by merbla** [comment] 2018-05-09 22:38
Thanks for the notes @josephgardner @MV10, I was referring specifically to the environment variables.

See 
* https://github.com/aspnet/Docs/issues/2012
* https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments.md

**Comment by MV10** [comment] 2018-05-10 10:05
The ASP.NET Core issue 2012 is that the _filename_ is case-sensitive (I saw that one while searching, too).

Looking at the [source](https://github.com/aspnet/Configuration/blob/dev/src/Config.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs#L51), the environment builder's `Load` method declares a case-insensitive dictionary:

```csharp
internal void Load(IDictionary envVariables)
{
    Data = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
```

I guess the real test (and I don't have Linux available) is whether key `A` from the environment will overwrite key `a` loaded from JSON after `Build` runs. Once configuration is built, there is no way to determine the origin of a given key.

**Comment by MV10** [comment] 2018-08-28 23:32
I finally had time to set up a Linux VM to see how _Configuration_ deals with environment variables, case sensitivity, and overlaying settings (if applicable on an OS with case-sensitive environment variables).

For Windows, I created one environment variable, `casesensitive = lowercase` and I also created a JSON config with `CASESENSITIVE : UPPERCASE`. For Linux, I use the same JSON file but I edited my user `.profile` to export `CASEsensitive = upperCASE` and `casesensitive = lowercase`.

The test app builds config twice, querying for all three settings each time -- once with environment variables before JSON, then again with JSON before the environment variables.

On both platforms, the last value wins, regardless of case.

Windows:
![image](https://user-images.githubusercontent.com/794270/44756231-ad8ad100-aaf7-11e8-8e82-dd6d84812d92.png)

Linux:
![image](https://user-images.githubusercontent.com/794270/44756373-546f6d00-aaf8-11e8-81e1-a590181393b7.png)

I didn't bother testing on OSX because it's a pain to start up that slug and copy stuff across the network, but I assume it'll be the same. And unfortunately I can't remember what the case-sensitivity issue was that I ran into a few months ago, nor can I explain the OP's issue.

The test:

```csharp
static void Main(string[] args)
{
    var appConfig = new ConfigurationBuilder()
        .AddEnvironmentVariables()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile(path: "appsettings.json", optional: false, reloadOnChange: true)
        .Build();

    Console.WriteLine($"env first casesensitive {appConfig["casesensitive"]}");
    Console.WriteLine($"env first CASEsensitive {appConfig["casesensitive"]}");
    Console.WriteLine($"env first CASESENSITIVE {appConfig["casesensitive"]}");

    appConfig = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile(path: "appsettings.json", optional: false, reloadOnChange: true)
        .AddEnvironmentVariables()
        .Build();

    Console.WriteLine($"json first casesensitive {appConfig["casesensitive"]}");
    Console.WriteLine($"json first CASEsensitive {appConfig["casesensitive"]}");
    Console.WriteLine($"json first CASESENSITIVE {appConfig["casesensitive"]}");

    Console.WriteLine("Any key...");
    Console.ReadKey();
}
```

**Comment by josephgardner** [comment] 2018-08-28 23:41
Did you forget to fix the casing in each `appConfig["casesensitive"]` to match the message? 

```cs
Console.WriteLine($"json first CASESENSITIVE {appConfig["casesensitive"]}");
```

Should be

```cs
Console.WriteLine($"json first CASESENSITIVE {appConfig["CASESENSITIVE"]}");
```

?

**Comment by MV10** [comment] 2018-08-28 23:49
@josephgardner Thanks ... but the screenshots were taken after I fixed that. I use one of those multi-page clipboard utils and pasted the wrong version. But code in the post is now updated. No change in conclusion.

**Comment by MV10** [comment] 2018-08-29 11:39
@josephgardner After playing around with some variations, now I see what you're talking about -- it looks like _parameter-matching_ is case-sensitive (the "args" entries, specifically). Going back to your earlier posts, I looks like you realized this, but it wasn't clear to me from the description (no big deal, we got there in the end). I took the liberty of editing the issue title. This potentially affects all configuration sources. Now I'm reminded that's also what I ran into working on the SQL sink. (I sometimes wonder how many millions of man-hours have been wasted on case-sensitivity...)

It turns out (fortunately for me) that this can be tested and reproduced in Windows. Even though the name of an environment variable is case-insensitive in the sense that `A` and `a` can't co-exist and either will match in a lookup, case is nonethless _preserved_, so the following works for `theme` but not `Theme` or `THEME`:

![image](https://user-images.githubusercontent.com/794270/44785047-95e63380-ab5d-11e8-9e9f-91ab26044e79.png)

I'll take a look at the project shortly. Technically I'm supposed to be packing for a vacation, but maybe it's an easy fix. If not, I'll work on it next week.

**Comment by MV10** [comment] 2018-08-29 12:29
For argument matching, the culprits are the `suppliedArgumentValues` checks [here](https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs#L347-L348). This test is only used to locate a matching method. The parameters themselves are passed to `Invoke` positionally.

```csharp
internal static MethodInfo SelectConfigurationMethod(IEnumerable<MethodInfo> candidateMethods, string name, Dictionary<string, IConfigurationArgumentValue> suppliedArgumentValues)
{
    return candidateMethods
        .Where(m => m.Name == name &&
                    m.GetParameters().Skip(1).All(p => p.HasDefaultValue || suppliedArgumentValues.Any(s => s.Key == p.Name)))
        .OrderByDescending(m => m.GetParameters().Count(p => suppliedArgumentValues.Any(s => s.Key == p.Name)))
        .FirstOrDefault();
}
```

In my earlier reply I questioned whether this is a good idea given everything in .NET is case-sensitive, but after thinking about it more, case-insensitivity is safe here. The following code is not valid in .NET (or at least in c#, though I assume this limitation extends to the CLR), the IDE flags the second one with "Type 'Program' already defines a member called 'Foo' with the same parameter types."

```csharp
string Foo(string value) => "lowercase arg";
string Foo(string VALUE) => "uppercase arg";
```

If the CLR can't differentiate and _MES_ doesn't differentiate, that's good enough for me!

**Closed** 2018-09-16 10:33 UTC
Labels: bug, up-for-grabs
