### ISSUE TITLE
No "None" option for minimum log level

### ISSUE THREAD

**Issue by jez9999** [serilog/serilog-settings-configuration#207] opened 2020-03-11 09:18 UTC
In ASP.NET Core's default logging configuration, you can specify "None" as minimum logging level to suppress all output from that logging source.  In Serilog, it looks like the closest is Fatal, which will obviously still log Fatal errors.  None should be added.

**Comment by skomis-mm** [comment] 2020-03-11 10:16
Hi, @jez9999 . It is duplicate of https://github.com/serilog/serilog/issues/1049

**Closed** 2020-03-11 22:09 UTC
Labels: duplicate
