### ISSUE TITLE
Can you allow WriteTo to take a hash as well as an array?

### ISSUE THREAD

**Issue by zippy1981** [serilog/serilog-settings-configuration#109] opened 2018-05-04 17:21 UTC
I posted this self answer on stackoverflow last night:

https://stackoverflow.com/questions/50167228/appending-arrays-in-from-appsettings-environment-json-to-appsettings-json

TL;DR; if I want to have one sink in appsettings.json and one in appsettings.development.json I need to use funky array notation syntax. The problem is the two files need to know about the order of arrays. The config files would be much more elegant if  WriteTo could take a hash table. Perhaps in that case the Key could be the Extension method to add the sink and the value could be the args array. Of course the sacrifice there is you could not use a sink twice. In many cases that could be considered a feature.

**Comment by nblumhardt** [comment] 2018-05-04 23:09
Thank you for the note 👍 

I think this is a duplicate of #49 (which would be really great to make some progress on).

**Comment by skomis-mm** [comment] 2020-05-13 21:22
For a reference about how to use custom keys for array items see [comment](https://github.com/serilog/serilog-settings-configuration/issues/70#issuecomment-627022808).  Discussion about simplifying syntax is in #49 .

**Closed by skomis-mm** 2020-05-13 21:22 UTC
Labels: duplicate
