### ISSUE TITLE
minimumlevel not support 'None'

### ISSUE THREAD

**Issue by bidianqing** [serilog/serilog-settings-configuration#193] opened 2019-08-08 09:37 UTC
![image](https://user-images.githubusercontent.com/12196280/62692290-fbe06980-ba02-11e9-8e67-e0e39570a8ac.png)

**Comment by skomis-mm** [comment] 2019-08-08 09:59
Hi, @bidianqing. In that section you need to use Serilog log levels
https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEventLevel.cs

**Comment by bidianqing** [comment] 2019-08-08 10:53
I think that should be supported

**Comment by nblumhardt** [comment] 2019-08-09 04:56
Thanks for the suggestion. I think this is a duplicate of #1049 - is that correct?

**Comment by Sonorpearl** [comment] 2019-09-18 15:34
Verbose is the equivalent of None. ^^

**Comment by nblumhardt** [comment] 2020-03-11 22:13
Thanks for the notes, here. We've spent some time analyzing this in the past and decided that the flow-on effect in the Serilog ecosystem makes it impractical to introduce `None`, but do check out _Serilog.Filters.Expressions_, where a filter expression `false` would have much the same effect.

**Closed by nblumhardt** 2020-03-11 22:13 UTC
